FROM node:latest

# Where we working?
RUN mkdir /data

# Install tools required for project
##RUN apt update

WORKDIR /data
RUN git clone https://github.com/typicode/jsonplaceholder.git  
RUN npm install jsonplaceholder
COPY run.sh /data/run.sh
RUN chmod 755 /data/run.sh

EXPOSE 3000

# This results in a single layer image
ENTRYPOINT ["/data/run.sh"]
